### ISSUE TITLE
Right click menu on task

### ISSUE THREAD

**Issue by mimmori** [QTodoTxt/QTodoTxt#107]
It would be great to have the right click menu on tasks for run some commands (delete, complete, change priority).

**Comment by funkyfuture** [comment]
imo, that would overload the minimalistic design of qtodotxt.

what about a selectable horizontal, restraint textwidget at the top or bottom that lists all keyboard-commands?

**Comment by kmicc** [comment]
I personally would appreciate a contextual menu very much. It's clearly a missing feature. @oroulet: You wrote that this could be done with "a few lines of code". Would it be possibe that you provide these few lines? :-)

**Comment by oroulet** [comment]
I was wrong this was not a few line but one :-) https://github.com/mNantern/QTodoTxt/commit/65186512a195162d55ac5f46e45d145fc6ef141f

more informatin there https://github.com/mNantern/QTodoTxt/pull/151

**Comment by kmicc** [comment]
Great! Thank you! I just merged it into https://github.com/kmicc/QTodoTxt.

**Comment by kmicc** [comment]
Implemented with #151.
