### ISSUE TITLE
"Open with" independent files

### ISSUE THREAD

**Issue by daducci** [QTodoTxt/QTodoTxt#112]
It would be nice to have the possibility to open specific file by simply double clicking on them. I usually have several .todo text files in my repositories, to share the to-do with other developers. I know there is the "-f" flag but, in Mac for example, when I double click I cannot specify the "-f" flag during the call (or I did't find the way to). I guess it would suffice to simply make the "-f" flag as being the first (optional) parameter in the command line. What do you think?

**Comment by funkyfuture** [comment]
do we actually need the `-f`-flag?

**Comment by raabf** [comment]
The default syntax for passing a file to an command, is to add the file path as parameter and not as option (except for files that have an default path, like configuration files). So providing the file path as parameter would be the more usual way and so more intuitive.

**Comment by kmicc** [comment]
@daducci: Does #158 solve this issue for you?
