### ISSUE TITLE
Add excluding filter

### ISSUE THREAD

**Issue by AnderRasoVazquez** [QTodoTxt/QTodoTxt#115]
I think that we should have **a filter that excludes things**. Maybe next to the filter, another textbox that says something like "exclude". That would be nice for projects like +some_day or similars that you don't need right now.

Another approach are the custom filters (Rhino JavaScript engine) that uses SimpleTask https://github.com/mpcjanssen/simpletask-android. Those would be perfect, because they will please everyone. https://github.com/mpcjanssen/simpletask-android/blob/master/src/main/assets/javascript.md

**Comment by mNantern** [comment]
@monotasker added support for OR and AND in issue #47 but we have to add support for NOT indeed.

Using javascript seems to complicate for me.

**Comment by kmicc** [comment]
Implemented with #152
