### ISSUE TITLE
[v1.4] Crash at startup on windows if config file is marked as hidden

### ISSUE THREAD

**Issue by Schroedingers-Cat** [QTodoTxt/QTodoTxt#116]
QTodoTxt won't start if it's configuration file is marked as hidden on Windows (only 7 tested). All versions up to v1.4 are affected by this bug. Steps to reproduce:
1. Start QTodoTxt for the first time
2. Configure some stuff like path to your todo.txt etc.
3. Close the application
4. Navigate to %userprofile% and hide the file .qtodotxt.cfg
5. Try to start the application

**Comment by mNantern** [comment]
Wow, why would you do that ?

Have you something into C:\Users<Username>\AppData\Roaming\QTodotxt\ when you try to run QTodoTxt ? (I don't have a Windows now to test)

Thank you !

**Comment by Schroedingers-Cat** [comment]
QTodoTxt only saves the files `stderr.log` and `stdout.log` to `%appdata%\QTodoTxt`. However, it's configuration file is saved at `%userprofile%`, which corresponds to `C:\Users\SOME_USER\`. So everytime I navigate to my home folder, I see the file `.qtodotxt.cfg` which I really don't want to see there all the time. 

I tried hiding the file, but then QTodoTxt won't start. This is the content of the `stderr.log` if starting the application fails:
>Traceback (most recent call last):
  File "qtodotxt.pyw", line 28, in <module>
  File "C:\Users\Matt\Desktop\Développement\QTodoTxt\qtodotxt\app.py", line 63, in run
  File "C:\Users\Matt\Desktop\Développement\QTodoTxt\qtodotxt\ui\controllers\main_controller.py", line 78, in show
  File "C:\Users\Matt\Desktop\Développement\QTodoTxt\qtodotxt\ui\controllers\main_controller.py", line 238, in openFileByName
  File "C:\Users\Matt\Desktop\Développement\QTodoTxt\qtodotxt\lib\settings.py", line 31, in setLastOpenFile
  File "C:\Users\Matt\Desktop\Développement\QTodoTxt\qtodotxt\lib\settings.py", line 96, in _setData
  File "C:\Users\Matt\Desktop\Développement\QTodoTxt\qtodotxt\lib\settings.py", line 100, in _save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Don David/.qtodotxt.cfg'

**Comment by funkyfuture** [comment]
unless you come up with a concept how that would be solved, i tend to mark that wontfix and close this issue.

**Comment by Schroedingers-Cat** [comment]
It could be solved my saving configuration files where they belong. 
In Windows, user data that does not depend on the machine should be saved at `%appdata%`. An example for that would be settings like "Add_create_date" or "last_open_file". This should be saved at `C:\Users\USERNAME\AppData\Roaming\QTodoTxt\settings.cfg`. 
User Data that depends on the machine (and because of that should not be roamed) is saved at `%localappdata%`. This includes settings like `view_position` or `view_size`and should be saved at `C:\Users\USERNAME\AppData\Local\QTodoTxt\settings.cfg`. 

Anyway, I do not understand why hiding a file removes write permission for QTodoTxt (last line of `stderr.log`). Additionall, the last line uses a mixture of slash and backslash to point to a path which could lead to the root of this bug?

**Comment by funkyfuture** [comment]
okay, and let's say the *ix-guys don't feel like inflating the code for an additional settings-file, what would be the location for the common windows-user who doesn't use roaming profiles, `Local`? Or rather `Roaming` for these who use roaming profiles? the latter suites both, right?

actually i think it may be a way to save the window's position in a dictionary with hostnames as key.

can you elaborate on your last paragraph? i don't get it.

**Comment by Schroedingers-Cat** [comment]
I just realized that "last_open_file" also is machine dependent, because the todo.txt could be placed in a different path on another machine. There is only "add_create_date" that should theoretically placed in roaming, so it is not that important to distinct between local and roaming. So the common place for the .qtodotxt.cfg file would be `Local`, preferably without the leading . (so `.qtodotxt.cfg` becomes to `qtodotxt.cfg`).

Post number 3 contains a logfile from QTodoTxt, when it is started with it's configuration file flagged as hidden on Windows. Reading the last line of this logfile, the error is `PermissionError: [Errno 13] Permission denied: 'C:\Users\Don David/.qtodotxt.cfg'`, which is puzzling because the file is only marked as hidden, not as write-protected and the permission default for a file in %userprofile%. Also, take a look at the path. `C:\Users\Don David` uses backslashes `\`, but `/.qtodotxt.cfg` uses a slash `/`. In my experience, mixing slashes for paths has led to problems.

**Comment by funkyfuture** [comment]
tasks:
- build a proper path in Windows platforms
- properly use path-methods to concentate paths

**Comment by funkyfuture** [comment]
@Schroedingers-Cat can you help with your abilities either by:
- implementing
- testing an implementation on Windows after pulling code with git and executing it from command line
?

**Comment by Schroedingers-Cat** [comment]
I have no experience with Python, but I'm familiar with git so I should be able to test your commits on Windows.

**Comment by kmicc** [comment]
@Schroedingers-Cat: You wrote on 29 Mar 2015:
> It could be solved my saving configuration files where they belong. 

With #194 we don't use the .qtodotxt.cfg anymore, we use QSettings instead. I didn't test it, but I think QSettings will save the configuration by default in the right place (probably in the registry on windows), so I close this issue here. If there's still a problem, just comment, reopen or create a new issue. Anyway, thanks for reporting this issue.

**Comment by Schroedingers-Cat** [comment]
Would you mind providing a pre-release build?

**Comment by kmicc** [comment]
I'm sorry, that's currently not possible, I don't know if / how the build scripts are working. That's an issue I planned to address later on.

Maybe you want to try out a manual installation of the current master branch? Having external users testing that version would be very helpful for us. You can also have a look on #190, we are planning to support installation via the python package manager pip.

**Comment by oroulet** [comment]
when we merge #190 (very soon I hope, it is just a formality) we cant create an installer by writing
python setup.py bdist --format=msi

**Comment by kmicc** [comment]
Then we maybe have the first volunteer for a beta test :-)

**Comment by Schroedingers-Cat** [comment]
I'd love to test version 1.5, but I don't have any experience with Python on Windows. So this may be noob questions ...
I installed WinPython 64 Bit 3.4.4 with QT5, downloaded the latest PySide (a *.whl file) and moved that to WinPythons Lib-Folder. Then I opened a terminal and started `python Path-To-qtodo.pyw`. However, I'm getting the following error:
```batch
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\scripts\ptpython.exe\__main__.py", line 9, in <module>
  File "C:\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\site-packages\ptpython\entry_points\run_ptpython.py", line 55, in run
    six.exec_(compile(open(a['<arg>'][0], "rb").read(), a['<arg>'][0], 'exec'))
  File "C:\Users\Don David\Desktop\QTodoTxt-1.5\bin\qtodotxt.pyw", line 26, in <module>
    from qtodotxt import app
ImportError: No module named 'qtodotxt'
```

**Comment by oroulet** [comment]
If you installed winpython, start a winpython shell and write pip install qtodotxt --pre. Then it will work

**Comment by Schroedingers-Cat** [comment]
Thank you!
The first start went successful. After quitting QTodoTxt 1.5 however, I got an error message (stopped working) and now, I cannot start QTodoTxt anymore:
```cmd
>python "C:\Users\User Name\Desktop\QTodoTxt-1.5\bin\qtodotxt.pyw"
Traceback (most recent call last):
  File "C:\Users\User Name\Desktop\QTodoTxt-1.5\bin\qtodotxt.pyw", line 26, in <module>
    from qtodotxt import app
  File "C:\Users\User Name\Desktop\QTodoTxt-1.5\bin\..\qtodotxt\app.py", line 8, in <module>
    from PySide import QtCore
ImportError: cannot import name 'QtCore'
```
