### ISSUE TITLE
CSS theming on QTodoTxt

### ISSUE THREAD

**Issue by cjrobe** [QTodoTxt/QTodoTxt#119]
I just found default.css in C:\Program Files (x86)\QTodoTxt\resources\css\default.css, and was pleased to find I can change the font, font-size, background colors, and other aspects of QTodoTxt.

I don't mind modifying the CSS code, but is there any chance that a simple GUI could be made for theming?

At very least, maybe add a small heading in the user documentation? I see there is some custom CSS variables like "selection-background-color." It would be nice to know if there are other custom variables that can be modified.

Thanks!

**Comment by mNantern** [comment]
Actually, I added a basic support for css for issue #59 (just for selection-background-color).

But indeed, we can use it more. If you want to write a wiki page about CSS in QTodoTxt I think you can, wiki is public normally.

Thank you !

**Comment by funkyfuture** [comment]
what about a `.qtodotxt.css` in the home-dir?!

**Comment by muteboy** [comment]
This would be great. I've moved from another client to QTodoTxt and I find the fonts too small. I'll investigate and find some more id's.

**Comment by oroulet** [comment]
Should be a program called qtconfig installed with qt. There you can select
font

**Comment by muteboy** [comment]
I'm using QTodoTxt on Windows at work, so I don't think that's an option.

**Comment by kmicc** [comment]
I can confirm that the fonts under Windows are to small (Linux is ok, so we need something platform dependent).

**Comment by PKEv** [comment]
look  #270

**Comment by PKEv** [comment]
closed via #338
