### ISSUE TITLE
Rebase the autocomplete- and duedate-feature related commits

### ISSUE THREAD

**Issue by funkyfuture** [QTodoTxt/QTodoTxt#134]
as I'm currently running tests, i found a non-working one in `test_autocomplete_lineedit.py`. i then stumbled across quiet a mess of commits by @jo-tud. can you please rebase your commits into two, one for the autocomplete-feature, one for the due date-filter?! if you have any questions about the proces, feel free to ask.

therefore, please don't merge something new into `master` until this is cleaned up.

we should also define some standards into a `CONTRIBUTING.md`. I think running `flake8` while ignoring _E501_ (too long lines) is a good idea to propagate. also, i found the duedate-code quiet full with boilerplate-code. we should avoid this to lower maintenance.

**Comment by jo-tud** [comment]
I don't have much experience with git, yet, and when the pull requests got messed up I was releived I coud get everything to a working state again. ;)
I'd be glad if you could help me to clean that up. So how would I go about rebasing these commits?

**Comment by funkyfuture** [comment]
yeah, it will be really messy. 

what would help from your side, in a nutshell:
- checkout to the 1.4-tag
- locally create a branch for each feature (autocomplete and duedate) from that point
- cherry-pick the commits related to a feature  into the corresponding branch
- squash all picked commits into one
- notify me

if you mail me a jabber-contact, we may have a chat.

i will try to do a rebase in an extra branch and ask anyone who contributed to review it.

**Comment by funkyfuture** [comment]
i already gave it a try, and really @jo-tud, it would be of great help if you condensed your work into two commits.

but i also saw that the autocomplete-feature also extends the due-feature, in these regards i will update the sketched process in the post before. so eventually the extension sits on top of the first commit. but in your case it will be quiet a nasty business as there's a lot of 'hin & her' between the features in the commit history. i understand that, but in the long term it's better do discipline oneself to not work on different tasks simultaneously. but as you will learn rebasing you'll be able to manage that better. and i can recommend to make yourself familiar with `git stash …`.

also a good read on squashing commits: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

have fun! :-P

really, rebasing isn't that simple as it has a lot of side effects the more complex it gets. be aware that it won't propably not turn out the way you intend on the first approach.
it took me few days and couple of tries until i more or less learned what to consider. and here i am, still learning. as soon as you think the shit hit the fan: `git rebase --abort` is your friend.

**Comment by funkyfuture** [comment]
one last thing: please check with Markus if it's okay that you also squash his commits into yours. this means his authoring credits will be lost, but that'd make it easier.

**Comment by funkyfuture** [comment]
phew, i was curious, so here's it: https://github.com/funkyfuture/QTodoTxt/commits/rebase-master

please review this.

tests are passing, but i'd appreciate if you rewrote the doctests to unittests.

also, i have some critics on the filters:
- the code is very redundant, you should use class-inheritance
- completed tasks are filtered out, this is not reflected in the filter-class' name and should imo not done at this point. rather filters should be combined.

**Comment by funkyfuture** [comment]
okay, i pushed the rebased master.

@jo-tud are you motivated to fix the issues regarding the tests and filter-classes? if so, i would then squash it into the latest commit.

**Comment by jo-tud** [comment]
Thanks for all your work up to here, that was great! Problem is:
I'm currently very busy with other projects - so I don't plan on working on this within the next couple of days, sorry.
