### ISSUE TITLE
Support for 'file://' hyperlink protocol to link local resources to tasks

### ISSUE THREAD

**Issue by ghost** [QTodoTxt/QTodoTxt#139]
Standard http|ftp URLs are captured and presented as hyperlinks in the main tasklist.

It would be useful to also support the 'file://' hyperlink protocol to link local resources to tasks. A particular usage case would be a task like "Update contacts worksheet file:///my/local/directory/file.txt with new client information".

It appears from my investigations that you use xgd-open to open a hyperlink target. The 'file://' protocol is supported by xgd-open (at least on on Ubuntu 14.04).

Is it possible to get the program changed to recognise local file hyperlinks?

**Comment by SimonChristopherCropper** [comment]
It appears that the hyperlinks are processed by _htmlizeURL() in task_htmlizer.py.

I have compiled some regex for Windows and Linux using online resources and tested them on kiki. They work in kiki but do not work properly in your program. It appears that the regex.sub() is getting confused by the brackets.

I am posting the regex here to facilitate testing on your side. Hopefully you can make the subroutine work and the hyperlink will operate as expected.

Windows fullpath match
(file://)([a-zA-Z]:\\)?[^\x00-\x1F"<>\|:\*\?/]+\.[a-zA-Z]{3,4}$
Linux  fullpath match
(file://)((?!.*//.*)(?!.*/ .*)/{1}([^\\(){}:\*\?<>\|])+\.[a-zA-Z]{3,4})$

**Comment by SimonChristopherCropper** [comment]
Working code for web and linux...

```python
def _htmlizeURL(self, text):
        regex = re.compile(r'((file://(?!.*//.*)(?!.*/ .*)/{1}([^\\(){}:\*\?<>\|])+\.[a-zA-Z]{3,})|'  # 
            r'(?:http|ftp)s?://'  # TODO what else is supported by xgd-open?
            #TODO add support for user:password@-scheme
            r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|'  # domain...
            r'localhost|'  # localhost...
            r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|'  # ...or ipv4
            r'\[?[A-F0-9]*:[A-F0-9:]+\]?)'  # ...or ipv6
            r'(?::\d+)?'  # optional port
            r'(?:/?|[/?]\S+))(\s|$)', re.IGNORECASE)
        return regex.sub(r'<a href="\1">\1</a> ', text)
```
note I removed the /2 in the sub() command as it appeared irrelevant.

**Comment by SimonChristopherCropper** [comment]
Now included functionality for local files, local directories and email links to be recognised. See my pull request for further details.

**Comment by mimmori** [comment]
I have tested in windows but it __doesn't work yet__. It would be very useful function for speedup activities.

**Comment by oroulet** [comment]
And what are the symptoms? What task string?

**Comment by mimmori** [comment]
I tried some schema...

- do something file://C:\my_file.txt 
- do something file://C:/my_file.txt
- do something file:///C:/my_file.txt

anyhow it hasn't been recognize as link and shown as simple text

**Comment by oroulet** [comment]
Does it work with a http address? It is hard to test c:\ ting on linux...

file://home/xxx works perfectly on linux...maybe it is a windows things

**Comment by oroulet** [comment]
seems to be very hard to install pyside on windows..Anyway I do not understand how this can fail only on windows. Are you sure you run the correct branch? you do not have several installations that overrride each others?

**Comment by oroulet** [comment]
Sorry I see this is another bug request!! The working code is there https://github.com/QTodoTxt/QTodoTxt/pull/230 and it is not merged yet. but hopefully soon, as it makes the code much shorter and fixes bugs

**Comment by mimmori** [comment]
Ok, thanks... I will try to merge in my local copy...

**Comment by kmicc** [comment]
There has been a pull request (#140) for this issue, which was to 90% ok. Unfortunately, the pr author decided to close that pr instead of solving the remaining (minor) problems, so the pr stayed unmerged. Indeed, having the proposed functionality would be useful.

**Comment by oroulet** [comment]
>> There has been a pull request (#140) for this issue, 

In my opinion the proposed solution was completely broken, over complicated and did only support a few pre-defined url format.  #230 is only one line and maybe still too somplex, maybe everything with a "protocol:" tag could be presented as a url

I uploaded alpha version if someone want to test
pip install qtodotxt --pre

**Comment by oroulet** [comment]
done in 1.6beta
