### ISSUE TITLE
QTodoTxt build fails...

### ISSUE THREAD

**Issue by the-this-pointer** [QTodoTxt/QTodoTxt#149]
Hi! I edited the code and implemented task percantage for personal use but I can't build this project!!!
I installed prequisites also PyQt (All of these are x64) and on Win7 X64 I'm trying to build...

the reason of failing is the QtGui doesn't load successfully, and I'm sure the Qt dll files are in Path variable... this is exact error message:
"
.
.
in <module>
    from PySide import QtGui
ImportError: DLL load failed: %1 is not a valid Win32 application.
"
Any idea?!

**Comment by zefilipe** [comment]
download installer of pyqt 5 at the bottom of this link
https://www.riverbankcomputing.com/software/pyqt/download5

Install it, next, next ... and this is done, qtodotxt pre opens ok ;-)
Regards
