### ISSUE TITLE
input dialog fails to open - input dialog autocomplete problem

### ISSUE THREAD

**Issue by alperyilmaz** [QTodoTxt/QTodoTxt#166]
When I press ctrl+n or ctrl+i, input dialog didn't show up.
I ran the application from commandline and then the error message below was printed:
  File "/home/alper/softwares/qtodotxt/QTodoTxt-master/bin/../qtodotxt/ui/controls/autocomplete_inputdialog.py", line 46, in _populateKeys
    EOM = 'due:' + (date.today().replace(month=date.today().month+1, day=1)
ValueError: month must be in 1..12

I changed the "month+1" to "month" in line 46. Now it works.

**Comment by kmicc** [comment]
Thanks for reporting this issue and providing a workaround - but this issue seems to be already solved in #164.

**Comment by alperyilmaz** [comment]
In that case, software I'm using might not be the latest version.. Sorry about that..

**Comment by kmicc** [comment]
No need to apologize. The current release of QTodoTxt is quite outdated and the linked patch is currently waiting to be merged into the master branch. If you want to use a more recent (and patched) version of QTodoTxt, there are other sources floating around.

**Comment by kmicc** [comment]
Closed by #164.
