### ISSUE TITLE
request outliner features (workflowy / moo.do) inside qtodotxt

### ISSUE THREAD

**Issue by anacondaqq** [QTodoTxt/QTodoTxt#167]
```
Task
- SubTask1
-- SubTask Of Subtask1
-- SubTask2 of Subtask1
--- SubTaskof SubTask2 of Subtask1
```

I hope, you understand.

**Comment by kmicc** [comment]
I don't see a way to implement sub*tasks* within the [Todo.txt-Format](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format). But about what I personally thought about were sub*contexts* and/or sub*projects*. A possibility to do this could be the format
```
@context
@context-subcontext1
@context-subcontext2
@context-subcontext2-subsubcontext21
```
etc (same for +projects) and parsing/handling this in filters_tree_view.py. (I have this on my personal todo list, but not with the highest priority.)

**Comment by anacondaqq** [comment]
After a lot of time working with different outliners, i wish to say -> don't need to implement any features like this. Because in 99% of cases such extra sub-task, sub-sub-subtasks only confusing, and not helping to work. Current 1 task per project / context list -> ideal solution.
