### ISSUE TITLE
Agree on QTdodoTxt rules

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt#169]
current proposition is:

* do not push directly to master (only for merging)
* If a group member disagree => wait
* after 48 hours if 2 groups member approve request => merge
* After one week if 1 group member approve request => merge
* Simple bug fix can be merged directly

**Comment by kmicc** [comment]
Your proposed rules are ok and I don't disagree to them. But I'm not sure whether it is really wise to exactly define times and needed group members for approval. For changes with a bigger impact one should maybe wait 2 or 3 weeks, changes with a low impact could maybe already merged on the same day. I also like the rule "Someone else than the pull request author merges" from your other project, which you didn't mention above. Therefore my proposition is:

1) Always create a pull request. Do not push directly to master (except if merging).
2) Don't merge your own pull requests.
3) Pull requests should be open an appropriate time to get a review. This doesn't apply to urgent bug fixes - these should be merged as soon as possible.

**Comment by mNantern** [comment]
I really like the proposals. They seem reasonable to me.
 
We should add them to the README (and we can always improve them later if something is wrong)

**Comment by oroulet** [comment]
do we agree on starting with kmicc rules then? and add deadlines later if
we find out it is necesary

**Comment by mNantern** [comment]
Yes !

**Comment by kmicc** [comment]
Thanks for agreeing on my proposal. Maybe number 2) is not the best idea in such a small group and in number 3) a hint what an "appropriate time" is would be helpful. Here my updated proposal:

> 1. Always create a pull request and wait for review. Do not push directly to master (except if you are merging a pull request).
> 2. If no one disapproves a pull request, you can merge it into the master branch. If someone (especially a group member) disapproves a pull request, wait and find a solution.
> 3. As a general rule of thumb, you should wait seven days before merging a pull request. For changes with a  bigger impact, you should wait a longer time. For urgent bugfixes the waiting time can be shortened. If one or more group members approve a pull request, the waiting time can be shortened too.

(I will be on holidays the next days so don't mind if I don't answer to questions.)
