### ISSUE TITLE
Support for non-latin or language indpenedent markup

### ISSUE THREAD

**Issue by damascene** [QTodoTxt/QTodoTxt#171]
Most markups in todo.txt files (priority (A)(B) and Date t:, due:) depends on Latin characters so a user of other alphabets like Arabic, Russian, Chinese would have to switch keyboard to write the markup. In RTL languages like Arabic, Hebrew, Persian and Urdu it add another problem because text will align to the left instead of the write. and those languages are read from right to left.

For example:
(A) شراء حليب
شراء حليب

![screenshot from 2015-12-22 14 05 26](https://cloud.githubusercontent.com/assets/411046/11954901/14b634ca-a8b5-11e5-97d8-ddd79cb325ac.png)

The first will be aligned to left and the second will be aligned to right in qtodo Another issue with due dates and threshold dates. (due: and t:)

It would be much better user to write todo.txt tasks in his language letters without having to use Latin characters.

My thought that many symbols that are available on every keyboard could be used like # & ^  and numbers could be used for priorities.
Or you could allow a markup or translation table so every one can set his own rules.

**Comment by kmicc** [comment]
Thanks for reporting these issue. I splitted it up into two issues, see #172 and #173. Hope this is ok for you.
