### ISSUE TITLE
Use other icons

### ISSUE THREAD

**Issue by kmicc** [QTodoTxt/QTodoTxt#175]
Especially needed for the toolbar, see #151.

I see 2 sources of icons:
1. https://doc.qt.io/qt-4.8/qstyle.html#standardIcon
2. http://tango.freedesktop.org/Tango_Desktop_Project resp. https://commons.wikimedia.org/wiki/Tango_icons
and tend to use the icons from the tango project (which are in the public domain, by the way).

**Comment by kmicc** [comment]
Unfortunatly, none of the svg-icons are shown in Windows 8 (png-icons are shown), turning this from a suggestion to a bug.

**Comment by oroulet** [comment]
Sounds like a qt bug more than anything else

**Comment by kmicc** [comment]
Implemented with #210.
