### ISSUE TITLE
Add option "Hide future tasks" to toolbar

### ISSUE THREAD

**Issue by kmicc** [QTodoTxt/QTodoTxt#178]
This relies on #151 and is the main reason, why *I* want to have a toolbar.

**Comment by oroulet** [comment]
done in 1.6beta

**Comment by zefilipe** [comment]
I do not realy whats it does ... ! 

I seen that had a option to hide / show future tasks, but do not had effect:

I created task and modify start date to 1 week or month ago, add a due task too long, and do not take any effect, clicking in hide / show future tasks :-(

Regards

**Comment by oroulet** [comment]
it applies to the t: tag
try
+QTodotxt test future t:2017-01-01
Seems to be badly documented
