### ISSUE TITLE
Use only QSettings for saving configuration

### ISSUE THREAD

**Issue by kmicc** [QTodoTxt/QTodoTxt#179]
This issue gets important with the first use of QSettings (in #151), but it is useful independent from #151.

It should be implemented by using the constructor `QtCore.QSettings()` (see https://doc.qt.io/qt-4.8/qsettings.html#QSettings-5) and setting
```
app.setOrganizationName("QTodoTxt")
app.setApplicationName("QTodoTxt")
```
once in `app.py`.

**Comment by oroulet** [comment]
#151 add the necessary architecture (very simple) and migrated one setting (LastOpenFile or similar). Now we just need to migrate the rest and remove custom file. I am not sure it is critical though :-)

**Comment by kmicc** [comment]
Maybe "Release Critical" is the wrong label. Read it as "fix before next release".

**Comment by kmicc** [comment]
Done with #194
