### ISSUE TITLE
add setup.py and upload to pip

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt#180]
This make installation and distribution to many more users easy
this might require moving around some files.

**Comment by oroulet** [comment]
setup.py is added in https://github.com/QTodoTxt/QTodoTxt/pull/186

I also pushed a beta version to pip, write:   sudo pip install qtodotxt --pre
If someone test it I will remove the beta flag

**Comment by kmicc** [comment]
Am I right that this is an additional installation method? If yes, than the wiki (page https://github.com/QTodoTxt/QTodoTxt/wiki ?) should be updated before closing this issue.

**Comment by oroulet** [comment]
merged and uploaded master to pip
