### ISSUE TITLE
Create preferences dialog

### ISSUE THREAD

**Issue by kmicc** [QTodoTxt/QTodoTxt#195]
I suggest creating a preference dialog which replaces the current four checkable options under Files->Preferences.

If we have such a dialog, it would be easier to add new preference options to QTodoTxt. Examples for such new preferences are a user defined number of priorities (#184), using numerical instead of latin priorities (#172) and surely some more.

**Comment by oroulet** [comment]
Agree. This dialog could also show current todo file etc

**Comment by kmicc** [comment]
See #226.
