### ISSUE TITLE
and/or/not conditions not functioning in filter (Win v1.4.0)

### ISSUE THREAD

**Issue by muteboy** [QTodoTxt/QTodoTxt#215]
To recreate, create a task with the following text:
"@Home @Work this is a test of filtering +Later +R2020"

Filtering gives the following results (filter text in quotes):

- "home" - returns all "home" tasks, including this one
- "work" - returns all "work" tasks, including this one
- "home work" - returns all tasks with "work" AND "home", including this one
- "home, work" - returns all tasks with "work" AND "home", including this one
- "home !work" - returns nothing
- "home ~work" - returns nothing
- "home, ~work" - returns nothing
- "home | work" - returns both "home" and "work" tasks
- "home | ~work" - returns all "home" tasks, but does not return all tasks NOT "work"

**Comment by kmicc** [comment]
Thanks for reporting this issue. Inverted search has been implemented with #152 and is therefore not included in release 1.4. Should work in current master and will be included in the next release.
