### ISSUE TITLE
Talking about QTodoTxt version 1.5

### ISSUE THREAD

**Issue by kmicc** [QTodoTxt/QTodoTxt#221]
Version 1.4 of QTodoTxt has been released in 9/2014. Many things changed since then: we have now due-filters, a toolbar, a new icon set, context menu, a not-search operator for tasks, multiline task view - to list only things that will be directly visible for the user. Users are also asking for funktionality which has already been implemented in the master branch, but not yet released.

I think after one and a half year the time has come to talk about a new release of QTodoTxt. When should version 1.5 be released? What should go in 1.5, what should postponed to 1.6?

My proposal: 
- Release of version 1.5 in 4-6 weeks, maybe earlier, but not later.
- I really would like to have #101 (multiline task editor) fully implemented in version 1.5. This is the functionality I currently miss the most. Maybe also one or another _minor_ bugfix or ui improvement.
- I also want version 1.5  to rely on long tested and reliable code. Oroulet, I really appreciate the work you are doing on refactoring the task classes etc. But I don't think these changes are ready for productive code. We should postpone such changes at the core functionality to a later version of QTodoTxt (i.e. version 1.6), so we have enough time for testing and fixing them. I'm also planning some major improvements / changes in the UI, and I will postpone them to a later version of QTodoTxt too.

I propose furthermore to create a release-1.5 branch based on 3aba364. In this branch should only release-related code be merged in. By using a separate branch, work on master doesn't need to be stopped due to the 1.5 release.

**Comment by oroulet** [comment]
I support the idea to release often. If you want to make immediatly a release based on master, I suggest to revert my commit about task comparison. It might break things. And also postpone multiline.

Concerning my new PR I am quite confident that it breaks very little, it makes the task code cleaner and more efficient. And if there is a bug at that level we will discover it very soon. But it can be 1.6 if you want. As long as it get merged soon in master....

**Comment by oroulet** [comment]
* Release of version 1.5 in 4-6 weeks, maybe earlier, but not later.

branch the code, fix things if you know there is a bug then release 1.5.0. you will never manage to test everything anyway after so many changes. then you can release 1.5.1 for bugfixes and we can release 1.6 in a month or so

* I really would like to have #101 (multiline task editor) fully implemented in version 1.5. 
As I wrote, better to postpone. Not sure everybody agrees on that one. Personally I do not understand what is the point with that. They were discussion/plans earlier about removing that window completely and do the editing directly in the taskview. That sounds a better idea in my opinion. Maybe it is possible to implement both things together but it will take some time and potentially break things ....

* I'm also planning some major improvements / changes in the UI, and I will 

OK. What do you want?

**Comment by kmicc** [comment]
> If you want to make immediatly a release based on master, I suggest to revert my commit about task comparison. It might break things. And also postpone multiline.

Ok, let's do it exactly this way.

> They were discussion/plans earlier about removing that window completely and do the editing directly in the taskview.

Could you provide me a link to that discussions? That would be helpful for me.

**Comment by kmicc** [comment]
Created the 1.5 branch. Will create some PR for it the next time (updating screenshots, doc, version number and similiar things).

**Comment by oroulet** [comment]
> Could you provide me a link to that discussions? That would be helpful for
> me.
>


Could not find it, there were no example code anyway. Just discussion. But
this is not hard to do. Qlistviewwidget allows to replace widget under
editing. So it probably just a few line of code.
But then when creating new task we need to decide where to insert it under
editing, not hard though...

**Comment by oroulet** [comment]
Created the 1.5 branch. Will create some PR for it the next time (updating
> screenshots, doc, version number and similiar things).
>

Sounds like things easier to do than creating a PR :-)

>

**Comment by sttrebo** [comment]
if your interested in a beta site, please let me know.  i am currently working on a autohotkey script that is adding some functionality as far a task creation goes so i'd love to see what you have been working on to see what i can do with my script.

thanks
steve

**Comment by oroulet** [comment]
Just clone master and test. It is not hard

**Comment by kmicc** [comment]
@sttrebo Beta-testing is of course very appreciated. Do you need binaries? Otherwise you could start testing with the 1.5 branch - there are no plans to add / remove / change any functionality within this branch.

**Comment by kmicc** [comment]
@mNantern: Would it be possible for you to provide binaries of the 1.5 branch (https://github.com/QTodoTxt/QTodoTxt/tree/1.5) (NOT the master branch!) for beta testing (and maybe also for the release later on)?

**Comment by kmicc** [comment]
Updated changelog for version 1.5, see https://github.com/QTodoTxt/QTodoTxt/wiki/Changelog.  A quite long list...

**Comment by mNantern** [comment]
@kmicc Yes ! I will try to do it this week-end

**Comment by zefilipe** [comment]
Hi,

Anyone can generate a QTodoTxt 1.5 beta installer ?

I tried to make a installer, but isn't easy, i installed ok python, but installing py2app (python setup.py install), it shows a error that only can be used in MacOs ... ! :-(

And i'm curious to test the new beta version ;-)

Regards

**Comment by oroulet** [comment]
I just updated pip. if you can use pip, you can get 1.5

**Comment by zefilipe** [comment]
Thanks, im using the pre version (1.5) ;-)
Regards

**Comment by kmicc** [comment]
Updated branch for resolving #228.

**Comment by mNantern** [comment]
At the moment I build QTT on my own computer (following https://github.com/QTodoTxt/QTodoTxt/wiki/Building-QTodoTxt-Binaries) but that's far from ideal.

Maybe we can setup some automatic build with [CircleCi](https://circleci.com) (for linux and OS X) and [AppVeyor](https://www.appveyor.com/) (for Windows).

They have both free plan for opensource project and can be integrated easily with Github. 

What do you think ?

**Comment by oroulet** [comment]
@mNantern . It would be great. I am also considering adding a release.py file that would create bump version, create tag and branch and upload to pipy so we can create releases more often. but that means we also need a solution to build and upload binary releases.. I known nothing about osX and Windows

**Comment by mNantern** [comment]
We can upload to [GitHub Release](https://github.com/QTodoTxt/QTodoTxt/releases) automatically from CircleCi or AppVeyor by using [GitHub API](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) I think

**Comment by RayDrew49** [comment]
Hi - just curious if 1.5 is any closer to being available as binary download - I would really appreciate being able to filter with the not (! ~) operator.
Best regards,

**Comment by oroulet** [comment]
1.5 is released but it looks like @kmicc has given up on releasing binaries. I am currently trying to polish things for a 1.6 release. When it is done, I may spend some time making binaries.... I do not really care, so it would be better if someone using these binaries steps in

**Comment by kmicc** [comment]
Well, my latest info is that @mNantern wanted to create the binaries. 

I'm definitivly not able to create binaries for OS X (didn't get managed to install PySide on the system I have access to), Windows would not be impossible, but difficult. I don't have the needed tools installed nor do I know where to upload the binaries, if I would have managed to create them.

I was also thinking about trying to use Qt Installer Framework. Never used it, so I don't know whether this would be a good idea.

**Comment by sttrebo** [comment]
i'm able to build the windows binaries/installer fine, but currently i can only build the v1.5.0 branch.  i'm not able to get the 'master' branch running yet either by running from the source or building an installer.
no idea how to upload the installer here so i can either share a link to my cloud drive or i can email to someone with the rights.  let me know if interested.

**Comment by oroulet** [comment]
we are now at 1.7 closing
