### ISSUE TITLE
done tasks appends </s> to end of the link and give link broken

### ISSUE THREAD

**Issue by zefilipe** [QTodoTxt/QTodoTxt#227]
Hi !

I had waiting for version 1.5, but this bug continues ... !

By example, i add a task like this:
`+QTodoTxt @Prefs Create preferences dialog https://github.com/QTodoTxt/QTodoTxt/issues/195`

That its good, when you do not remember the subject contents, open this link and see details ... !
When like me, works in a firm that you will be a organized tasks, it is realy good, at any moment i can see and see again the details of this issue !

While its a todo task, the link open ok :-)
But when complete this task (done task), it appends </s> to the end of this link, and gives link broken

In this case appear in browser
`https://github.com/QTodoTxt/QTodoTxt/issues/195</s>`
that is intrepreted as
`https://github.com/QTodoTxt/QTodoTxt/issues/195<`

and give a link broken error, only if manualy remove < at the end, it works fine ;-)
Regards

**Comment by oroulet** [comment]
fixed there, but it is huge rewrite, so I am not sure I did no break something

**Comment by oroulet** [comment]
I uploaded alpha version to pip : pip install qtodotxt --pre

**Comment by zefilipe** [comment]
Thanks, im tested, and now works well :-)

But i think two things:
1. it will be a space between end of the link and before completed date info
2. dates created and completed be better than in stable version (1.4), or be better like this
(created: 2016-03-06, completed: 2016-03-07)

Regards

**Comment by oroulet** [comment]
I just fixed a few things in #234
