### ISSUE TITLE
use PyQt and not PySide

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt#231]
Seems PySide is dying since nokia stopped working on it and it has no windows installer while pyqt comes with winpython for example and is much more reactive to new qt releases
Replacing dependency should no be hard, but will require to modify almost all files.
opinion @kmicc ? @mNantern

**Comment by mNantern** [comment]
I agree, PySide seems (almost) dead: http://code.qt.io/cgit/pyside/pyside.git/stats/

**Comment by kmicc** [comment]
Seems to be a bigger change for me. As long as we don't move away from Qt I'm neutral here. Of course it would be nice to be able to rely on Qt versions newer than 4.8. 

I'm in doubt with "replacing dependency should no be hard". Maybe we should create a separate branch for doing / testing the transition?

**Comment by oroulet** [comment]
I did it: https://github.com/QTodoTxt/QTodoTxt/pull/233
Tok 30 minutes. might be bugs, but it seems to work correctly. tests are broken

**Comment by oroulet** [comment]
done in 1.6

**Comment by XRevan86** [comment]
The situation appears to have been reversed with the release of [Qt for Python](https://qt.io/qt-for-python).
