### ISSUE TITLE
INFO: formatted text

### ISSUE THREAD

**Issue by mimmori** [QTodoTxt/QTodoTxt#232]
In the sample image shown in the main project page seem that is possible to format text of the task (Bold/Underlined/Italic).

How can I do this? (markdown?)

https://github.com/QTodoTxt/QTodoTxt/wiki/screenshots/QTodoTxt_main_view.png

**Comment by oroulet** [comment]
HTML ! Just add HTML tags

**Comment by kmicc** [comment]
The todo file used for the screenshots can be found here: https://github.com/QTodoTxt/QTodoTxt/blob/master/examples/todo.txt

A link to the allowed HTML subset can be found here: https://github.com/QTodoTxt/QTodoTxt/wiki#tips
