### ISSUE TITLE
Delete a todo task, exits qtodotxt (pre version)

### ISSUE THREAD

**Issue by zefilipe** [QTodoTxt/QTodoTxt#235]
Hi !

Today im using qtodotxt pre, and tried in two ways:

- select the todo task and press delete key, or
- select the task, and open context menu, and select "Delete selected tasks" 

After this, qtodotxt is a somme seconds in systray and exits / close :-(

PS: im using windows 7

Regards

**Comment by oroulet** [comment]
just uploaded a new version with fixes. Can you try? --pre and --upgrade

**Comment by zefilipe** [comment]
it works well :-)
Thanks and regards

**Comment by oroulet** [comment]
close the issues when you know they are fixed :-)
