### ISSUE TITLE
Archiving completed tasks if auto archive not enabled

### ISSUE THREAD

**Issue by RayDrew49** [QTodoTxt/QTodoTxt#236]
Hello,

First - thanks for QTodoTxt - it's the todotxt UI that works best for me.

One question (on V 1.4 - Windows) - how do I archive tasks if I don't have auto archive enabled?

Best regards,

Ray

**Comment by oroulet** [comment]
I have not looked at that code yet, but I think it is currently not possible. But should be easy to add. patch welcome. Add an action for it.

**Comment by zefilipe** [comment]
Hi !

Today im completed a task using QtodoTxt pre version, and this tasks does not appears in completed items :-(

Its preferences, its very mutch better, thats good ;-)
I disabled auto archive and this works well ;-)

I think that auto archive be by default disabled, and in future we can think in a feature that archives done tasks of the old year (by example: archive done tasks of 2015)

Regards

**Comment by oroulet** [comment]
You are right. The archive thing is broken.... I will have a short look, maybe disable it

**Comment by oroulet** [comment]
should be fixed in last pip version. Can you test? default is now auto_archive=False and added button to archive manually

**Comment by zefilipe** [comment]
i upgraded pre version, and its works ok ;-)
Regards
