### ISSUE TITLE
show / hide completed tasks if click hide its ok, but do not shows tasks in complete filters

### ISSUE THREAD

**Issue by zefilipe** [QTodoTxt/QTodoTxt#241]
Hi !

Today i upgraded my pre version of qtodotxt !
And wow, that a very great job, its amazing, realy this comunity its very breathtaking ;-)

I think the show / hide completed tasks very very good :-D
Its a feature so many times i like to had in qtodotxt, you can navigate in projects, contexts ... filters, and it shows (if marked show completed tasks), the todo and done tasks, and if hide only shows todo tasks, thats a very very top :-D

But if faults an exception: in complete filter, if its marked show or hide completed tasks, it be shows always the completed tasks, but for other filters, its ok ;-)

Regards

**Comment by oroulet** [comment]
also fixed in last commit
