### ISSUE TITLE
Projects and contexts filters to completed + todo tasks

### ISSUE THREAD

**Issue by zefilipe** [QTodoTxt/QTodoTxt#242]
Hi !

At start at this evening, i discovered another feature, that dont works as be expected !

For example:
todo tasks:
+QtodoTxt @Interface delevop a option to show / hide completed tasks
done tasks:
+QtodoTxt @Filter Improvement in filters, to show completed tasks if these option are selected

In interface it shows:

- Contexts
 -     Interface

- Projects
 -   Qtodotxt

If faults in contexts, item Filter of done task !
The some example be apply to projects ;-) 

Regards

**Comment by oroulet** [comment]
strange bug, the context filter fails if the name of the context is
Filter....

**Comment by oroulet** [comment]
ok now I understand, context and projects and not visible in tree if tasks
are completed. Will fix it when I get two minutes

**Comment by oroulet** [comment]
OK I pushed a solution which hopefully is intuitive. Can you have a look?

**Comment by zefilipe** [comment]
i updated qtodotxt pre version, by the command:
`pip install qtodotxt --pre --upgrade`

and dont have any changes to update ... !
Regards

**Comment by oroulet** [comment]
uploaded to pipy!

**Comment by zefilipe** [comment]
Hi !
I upgraded qtodotxt, and its fantastic, great job ;-)

I think that a feature may be very useful, is shows beyond the number of todo tasks, the number of the done tasks !

Example:
how has 8 done tasks and 2 todo tasks in context @Qtodotxt
At this times shows: Qtodotxt(2)
But in a future will be better and most complete shows: Qtodotxt(2,8)

Regards

**Comment by oroulet** [comment]
I agree. Will be next time, if you do not find bugs I will release 1.6.

**Comment by PKEv** [comment]
closed via #295
