### ISSUE TITLE
Not an Issue: How do I run the latest QTodoTXT code?

### ISSUE THREAD

**Issue by RayDrew49** [QTodoTxt/QTodoTxt#243]
Hi,

I'd like to run the latest QTodoTXT code. Could someone give me a quick example how I do this?
I have installed WinPython-32bit-3.4.4.1Qt5 and QTodoTxt-master (although I'm not sure if that's the latest code) but haven't been able to get it to run.
I have never used QT but have used Python in the past (10 years ago...)

Best wishes

**Comment by oroulet** [comment]
In the winpython directory you should have a script called settings or
admin, it starts a GUI where you can register Python to Windows (Google the
exact workflow). Then you can download qtodotxt and double click
qtodotxt.py in bin directory. It will work
Let us know if you find bugs. I never use Windows

**Comment by RayDrew49** [comment]
I've registered winpython via the console. There are 2 files in the QTodoTxt-master\bin directory: qtodotxt (with no file extension) and qtodotxt.pyw. If I run qtodotxt.pyw with pythonw.exe it exits immdediately - running with python.exe opens a console window and then immediately exits. I don't know if this is a bug or I'm just doing something wrong.

**Comment by oroulet** [comment]
To find out you need to open a terminal (cmd or powershell) then navigate
to bin directory and start the pyw file ( maybe rename to .py)

**Comment by RayDrew49** [comment]
This is what I get - (same with qtodotxt.pyw and renaming to qtodotxt .py)

```
C:\QTodoTxt-master\bin>C:\WinPython-32bit-3.4.4.1Qt5\python-3.4.4\python.exe qtodotxt.py
Traceback (most recent call last):
  File "qtodotxt.py", line 28, in <module>
    app.run()
  File "..\qtodotxt\app.py", line 72, in run
    controller.show()
  File "..\qtodotxt\ui\controllers\main_controller.py", line 94, in show
    self._updateView()
  File "..\qtodotxt\ui\controllers\main_controller.py", line 290, in _updateView

    self._view.restoreGeometry(self._settings.value("main_window_geometry"))
TypeError: QWidget.restoreGeometry(QByteArray): argument 1 has unexpected type 'NoneType'
```
I'll see if I can figure out...

**Comment by oroulet** [comment]
OK. stupide thing.  the line:

      self._view.restoreGeometry(self._settings.value("main_window_geometry"))

should probably be something like:

    self._view.restoreGeometry(self._settings.value("main_window_geometry", b""))

Can you test it? and send a pull request if you know how?

**Comment by RayDrew49** [comment]
Thanks - I have this working now. I didn't get anywhere with your suggestion to add another parameter. However, it struck me that as the application hadn't run before, maybe the issue was that there was no geometry or state to restore so I commented out the 2 lines below:
```
    def _updateView(self):
        # self._view.restoreGeometry(self._settings.value("main_window_geometry"))
        # self._view.restoreState(self._settings.value("main_window_state"))
```
The application then ran with the window in a default position. Once I had run the application I un-commented the 2 lines above and the application now runs fine and the window position and size is restored - since this appears to be set on the view close event.

**Comment by oroulet** [comment]
@RayDrew49 adding the second paramater should have fixed this... not sure. 
I just pushed some changes. if you run latest code, do no hesitate to report bugs or strange behaviour

**Comment by f8ttyc8t** [comment]
At first: I am a Python newbie. So I think described behavior is because of that fact.
My problem: immediately after firing up python, QTodoTxt terminates with result below:
D:\Development\Python\QToDoTxt.beta\QTodoTxt-master\bin>python qtodotxt.pyw
Traceback (most recent call last):
  File "qtodotxt.pyw", line 28, in <module>
    app.run()
  File "..\qtodotxt\app.py", line 72, in run
    controller.show()
  File "..\qtodotxt\ui\controllers\main_controller.py", line 172, in show
    self._updateView()
  File "..\qtodotxt\ui\controllers\main_controller.py", line 378, in _updateView
    splitterPosition = [int(x) for x in splitterPosition]
TypeError: 'int' object is not iterable

Same result occurs after installing it via "pip install --pre QTodoTxt"

Any idea how to fix that?

**Comment by f8ttyc8t** [comment]
Additional note/workaround:
After commenting out lines #378 and #379 of file "\qtodotxt\ui\controllers\main_controller.py" app starts up as expected.

**Comment by oroulet** [comment]
Thank you for the report. This was an issue when having no config file (of
course all developers have, this is why we did not catch it). I pushed a
fix, try to update with pip

**Comment by f8ttyc8t** [comment]
Great! Works like a charm now!
