### ISSUE TITLE
Help icon

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt#246]
running v1.5.0, latest sources.  On the new and edit task dialog, when you select the '?', the only thing that happens is the screen cursor changes to a red circle with a line thru it.  the cursor stays changed until another selection is made.
![dsc_0136](https://cloud.githubusercontent.com/assets/2676482/14658842/c19b4510-064b-11e6-9a49-558a29bbf63c.JPG)

**Comment by oroulet** [comment]
seems to be something very windows specific, this icon does not exist on linux...nnot sure how to fix such a thing...

**Comment by PKEv** [comment]
closed via #293
