### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt#247]
running v1.5 (latest sources under windows).  context menu (right click) works fine when a task is selected, but it would be nice to be able to create a new task from a context menu also (right-click - new).

thanks

**Comment by oroulet** [comment]
How did you install 1.5? I am trying to stabilize 1.6 (the latest code on master github) could you try this one? It has many many changes...

**Comment by sttrebo** [comment]
i ended up building a windows installer per the instructions, pretty easy and worked just fine.  i have tried running v1.6 from the source but have not had any luck at all.  not sure what i need to do differently.  if i can run v1.5, shouldn't v1.6 run also or is there a different Python/Qt environment?

**Comment by oroulet** [comment]
1.6 requires pyqt5 and  not pyside/qt4.This should betheo nly difference

**Comment by oroulet** [comment]
And pyqt5 comes with winpython. So no need to compile anything. Should take
5 minutes download

**Comment by sttrebo** [comment]
must be something with my system.  this is what i get.  can anyone help?

installed python-3.4.4.amd64.msi
installed PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x64.exe
from cmd line confirmed that python34 is in path
from cmd line (in /bin directory) ran python.exe qtodotxt.pyw
![python error](https://cloud.githubusercontent.com/assets/2676482/14714951/e0873d34-079b-11e6-9cf3-ce128428ca02.jpg)

**Comment by oroulet** [comment]
As the error days install dateutil module. Not sure how to do it on Windows.
It is probably easier to install winpython which has all dependencies

**Comment by sttrebo** [comment]
finally got winpython to load it and run it ok.  for some reason my system balks at running winpython from 'my apps' (i guess it didn't like the space between 'my' and 'apps'.

**Comment by oroulet** [comment]
Please close issues that are fixed. Is this one still relevant?

**Comment by sttrebo** [comment]
context menu 'new' is still relevant and would be nice in v1.6.  would you prefer i open up a new issue instead of threading off this one?
