### ISSUE TITLE
v1.6 (4/21 files) early feedback

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt#248]
now that it's running for me (Win7-Enterprise) a few things i've noticed:

1. Help icon, same non-function as I reported for v1.5
2. Toolbar icon for show filters has no .bmp
3. Toolbar icon for show future tasks has no .bmp
4. Help-About shows v1.5.0
5. enable system tray in settings doesn't seem to do anything

do you have a change log of v1.6 over v1.5?

**Comment by oroulet** [comment]
You mean svg icons are still not supported on Windows?

>

**Comment by sttrebo** [comment]
I'm no expert, but I came across this...
https://medium.com/@webalys/die-png-die-how-to-use-vector-icons-in-your-apps-d884c9c63e93#.kf3n6bm8f

**Comment by oroulet** [comment]
What are the symptoms? Missing icons?

**Comment by sttrebo** [comment]
yes, but the buttons work fine.
![clipboard01](https://cloud.githubusercontent.com/assets/2676482/14746376/23502478-0864-11e6-955e-3113bd47384f.jpg)

**Comment by oroulet** [comment]
commited a fix fo all thes, but the help stuff. Can you check it works with latest master?

**Comment by sttrebo** [comment]
2, 3, 4, &5 all look good.

thanks
