### ISSUE TITLE
Building v1.6 for Windows

### ISSUE THREAD

**Issue by f8ttyc8t** [QTodoTxt/QTodoTxt#252]
Tried to build Windows binarie as described (involving Inno Setup, using non-unicode as well as unicode version).
Using WinPython WinPython-64bit-3.4.4.2Qt5, I received error:

error: [Errno 2] No such file or directory: 'C:\\Python34\\Lib\\site-packages\\PyQt5\\plugins\\imageformats\\qico4.dll'

For sure, my python installation is not located there.
Since I've installed PyQt5, dll name is "qico.dll" rather than "qico4.dll".
Replacing this string with existing one solves that.

Also, installed version identifies itself as version 1.5.0 because that's defined in file "installer.iss" in #define MyAppVersion "1.5.0"

Anyhow - thank you very much for creating that gem of software development!

(Too bad, but build and successfully installed executable does not start at all. 
Maybe an expert is able to create binary package.)

**Comment by f8ttyc8t** [comment]
Addendum: 
if someone uses python 3.5.x as base python version, it is required to install python-dateutil before.
e.v. via "pip install python-dateutil"

**Comment by oroulet** [comment]
Try to modify the files under packaging/Windows . It looks like you already know what you need to modify :+) then send pull request

**Comment by f8ttyc8t** [comment]
Indeed. 
But I am still not able to support the project by delivering windows installer.

**Comment by oroulet** [comment]
What is you issue? do you get error message?

**Comment by f8ttyc8t** [comment]
No error message. Entire process (python setup.py py2exe) succeeds, install package is generated properly.
Also, installation of QTodoTxt using installer works as expected.
But QTodoTxt.exe won't start. Launched executable immediately terminates, without any log/message at all.

**Comment by oroulet** [comment]
even you start exe in a cmd window?

**Comment by oroulet** [comment]
even if you start exe in cmd window?

**Comment by f8ttyc8t** [comment]
Yes, tried cmd also.
I also switched between 32/64 bit version and unicode/standard version of Inno Setup.
Tried it in virtual machine (naked, without Python installed) as well as on machine having Python installed.

**Comment by f8ttyc8t** [comment]
Finally managed to build Windows installer including running qtodotxt.exe

Maybe someone can explain how to push modifications + installer?

**Comment by oroulet** [comment]
I will check this asap maybe I can make you a member of group. I created a
release on github , we can add binaries there

**Comment by mimmori** [comment]
Any news regarding the windows installer? I would use it at work where i cannot install Python...

**Comment by oroulet** [comment]
@mNantern can you invite @f8ttyc8t to qtodotxt group? Or even better make me an admin since it looks like I am the only maintaining the project for the time being.
@f8ttyc8t when you become a member you will be able to edit 1.6.0 release at https://github.com/QTodoTxt/QTodoTxt/releases and add your release there. Then it would be great if you can fix the links in the README to point there.

**Comment by f8ttyc8t** [comment]
Will upload as soon I get access - will be my pleasure!

**Comment by oroulet** [comment]
Let us hope @mnantern answers soon, otherwise we will need to fork again

**Comment by mNantern** [comment]
It's done @oroulet , have fun !

**Comment by f8ttyc8t** [comment]
Struggling with how to upload binary release. Might last some time till I found how to do...

**Comment by oroulet** [comment]
@mNantern thanks!

**Comment by oroulet** [comment]
@f8ttyc8t I just invited you to become a member. when you have accepted I can give you the rights on this repository

**Comment by oroulet** [comment]
@f8ttyc8t if you have access you will be able to click edit on the release and the upload a binary. Let me know if it works by default or if I need to give you some special rights

**Comment by f8ttyc8t** [comment]
@oroulet thank you, now I had option to edit release.
Uploaded installer and replaced link in readme.md

**Comment by oroulet** [comment]
Thank you for the help! could you also create a push request with the changes you made to compile the code? and maybe update the wiki?

**Comment by f8ttyc8t** [comment]
Sorry, I am not familiar with git (using svn).
I've issued a push command. Is this enough or do I have do so something else?

**Comment by oroulet** [comment]
>> with git (using svn)

Well. Then you should really try to learn git. it makes development so much easier...
You need to clone repository
make your changes
push your changes
create a PR in github UI

If you really do not want to do that then do a copy paste of diff in github gist or whatever

**Comment by f8ttyc8t** [comment]
Steps 1-3 already done.
But do not know how to "create a PR in github UI" 
(Honestly, I am overcautious because I am afraid to mess up your repo)

**Comment by oroulet** [comment]
>> Honestly, I am overcautious because I am afraid to mess up your repo)

made a small mistake here:
clone -> fork
in github go to qtodotxt repository and click "FORK"
clone locally
make changes
push 
the changes should then be visible on your fork in github and a green button should wayt for you saying: create a pull request.

**Comment by f8ttyc8t** [comment]
Done (probably...)

**Comment by f8ttyc8t** [comment]
Updated wiki also.
