### ISSUE TITLE
1.6 changelog?

### ISSUE THREAD

**Issue by cjrobe** [QTodoTxt/QTodoTxt#256]
Apologies if I'm missing it but I don't see a changelog for 1.6. Just this old wiki page that hasn't been updated in a while.

https://github.com/QTodoTxt/QTodoTxt/wiki/Changelog

Thanks and look forward to trying the new release.

**Comment by oroulet** [comment]
here: https://github.com/QTodoTxt/QTodoTxt/releases

can you update the wiki?
