### ISSUE TITLE
Autoarchive does not work (windows version)

### ISSUE THREAD

**Issue by f8ttyc8t** [QTodoTxt/QTodoTxt#258]
Even if "AutoArchive" is activated in settings, QTodoTxt does not automatically archive them.

Manually initiating archivation (via "Archive Completed Tasks" button in upper toolbar) works as expected.

**Comment by f8ttyc8t** [comment]
Seems to be related to default settings.
Toggling settings seems to solve that.

**Comment by oroulet** [comment]
Can you find exactly when this happens? Is it the first start which is the
issue?

**Comment by f8ttyc8t** [comment]
Seems to be my fault.

I've tried:
1.) installed new instance of WinPython (3.4.4QT)
2.) Stated python bin\qtodotxt.pyq
3.) Opened \examples\todo.txt file
4.) completed task (by pressing "x").  item was moved to sub-tree "Complete"
5.) opened settings. AutoArchive was already set to autoarchive
6.) toggled flag
7.) Closed app
8.) Opened app again (not sure whether step 7&8 are required)
9.) completed another task. This task immediately disappeared (I left "Show completed items" untouched, so they should remain visible under sub-tree "Complete")
10.) Initially completed tasks still remain (they remain in "Complete" and "All" sub-tree, but get drawn using strike trough font)

So, from my opinion, it's cause is how you treat auto archiving items.
1.) I think items only get auto-archived if they are completed AFTER settings are set to "AutoArchive". Which is perfectly good if this is apps intention.
2.)Items being completed while auto archive is unset, remain forever (but being stricken trough). This is also perfectly good if desired so.

Conclusion: I think this is my fault but not an issue.
I simply misunderstood mechanism of auto archive (I think it was implemented differently in v1.4)

**Comment by oroulet** [comment]
Thanks. Could you document behavior in wiki?

**Comment by f8ttyc8t** [comment]
Done.

Btw.: if there are no settings stored yet (e.g. during first run), auto safe is enabled by default but app behaves as if auto-archive is disabled.
By tracing settings I found user has to toggle settings once before settings get saved (and therefore could be used as expected)

**Comment by oroulet** [comment]
Ok thanks, will fix this

**Comment by oroulet** [comment]
found out I probably already fixed this in a PR I forgot to merge. Just pushed to master. Can you test it? if it works we'll make a 1.6.1 release

**Comment by f8ttyc8t** [comment]
Fixed the issue.
Added some additional fixes (version number now became 1.6.1 in About-dialog also, Windows-app now also has QTotoTxt-logo a icon).

How to proceed?

**Comment by oroulet** [comment]
Yes fork, make your changes and open PR again ( you can avoid fork and just update your clone if you want but it might require rebasing)

**Comment by oroulet** [comment]
Looks like you created a new release. You need to make a pull request with the fixes first :-).

**Comment by f8ttyc8t** [comment]
Hm.
I've forked and cloned project. Them I modified files. After that I've commited changes + pushed them.
So I assumed that's all I need to do.

Did I miss something?

**Comment by oroulet** [comment]
There is no commit from you todayso I guess you committed in your own branch. Then we should never commit directly to main branch, but commit to personal branch (as you did) then create PR. Thus other can review your changes and we avoid many errors...

**Comment by oroulet** [comment]
If you navigate to your fork on github, you will be asked if you want to create PR.

**Comment by f8ttyc8t** [comment]
Done.

**Comment by oroulet** [comment]
Your release was pointing to wrong commit. I recreated a v1.6.1 releae. Can
you re-upload your exe file? thanks

**Comment by f8ttyc8t** [comment]
Uploaded.
Sorry for causing troubles.
Code looks OK.

**Comment by oroulet** [comment]
No pb! Thanks for the help again!

**Comment by f8ttyc8t** [comment]
It's my pleasure!
