### ISSUE TITLE
Delete tasks

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt#261]
Sometimes I make a mistake and add a task that I don't want.  Looks like in v1.6 the 'del' doesn't work.  Was this intentional?

**Comment by oroulet** [comment]
This is now an option to enable delete action in preferences. Is it enabled?(need restart) if delete does not work when delete i enabled then it is a bug

**Comment by oroulet** [comment]
tested on my pc and it works when delete is enabled

**Comment by sttrebo** [comment]
found it, sorry about the false alarm.  no idea how i missed that.
