### ISSUE TITLE
Win32/Zwangi detected

### ISSUE THREAD

**Issue by pypardo** [QTodoTxt/QTodoTxt#263]
Hi All,
I apologize if it's not the right place.
**Win32/Zwangi** detected in qtodotxt.exe 1.6.1 for windows .
Detected with f-secure.
Regards

**Comment by kmicc** [comment]
Thank you for reporting this issue. This is absolutely the right place. Some questions:
* Did you download the exe from github?
* Did the alert occured in the downloaded "qtodotxt_1.6.1.exe" (i.e. in the installer), or in the installed files (i.e. after installing the software)?
* Could you repeat the scan with updated signatures of your virus scanner? Virustotal (see https://www.virustotal.com/de/file/de2821731a465d4ddd9abe80fdeaad7030dd0e3f635f7346fcaeeda3740d0e52/analysis/1467032542/) didn't found anything, and they are using f-secure too (among others).

**Comment by oroulet** [comment]
Isnt that email just spam?

**Comment by oroulet** [comment]
Of course the person that generated the exe might have had a virus..

**Comment by kmicc** [comment]
That would be the worst case. But it could also be a false positive. Had that problem with another virus scanner when compiling an empty Qt template project under windows.

**Comment by pypardo** [comment]
Hi All,
the alert occurs after an update to f-secure
When I first download qtodotxt installer (from github) nothing happened.
I use qtodotxt for some weeks, and after an anti-virus update it raises an
alert.
I'll retry an anti virus scan.

I do think it's a false positive, but I prefer to signal it .

Sorry for my poor english, I'm french :)

Regards
pierre

2016-06-27 22:20 GMT+02:00 kmicc <notifications@github.com>:

> That would be the worst case. But it could also be a false positive. Had
> that problem with another virus scanner when compiling an empty Qt template
> project under windows.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/QTodoTxt/QTodoTxt/issues/263#issuecomment-228863224>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AREtbVsp6183_TodMstAj-iOnNw2ckNnks5qQDCkgaJpZM4I9k0X>
> .
>



-- 
pp




*« Il faut toujours plus de temps que prévu, même en tenant compte de la
Loi de Hofstadter. » « I enjoy the massacre of ads. This sentence will
slaughter ads without a messy bloodbath. » « C'est un crime contre l'Etat,
le suicide. Un suicidé, c'est un soldat de moins, un contribuable de moins.
» « Man is the best computer we can put aboard a spacecraft – and the only
one that can be mass-produced using unskilled labour. » (Wernher Von Braun)*

**Comment by f8ttyc8t** [comment]
Hi Pierre,
did you cross-check it using on-line scanners also?
Because I created package but - at least I think so - my system is without any infections.

Anyhow, thank you for informing us/me!

(Btw. sorry for late reply, was at vacation...)

**Comment by pypardo** [comment]
Hi All,
and sorry for delay too.

I double-check (triple-check in fact) with other anti-virus and detect
nothing inside package.

My first anti-virus (F-Secure) has been updated since first virus
detection, and do not detect anything right now.
Maybe a bad F-Secure update.

I apologize for alerting you (but I think it's better thave a false alert,
instead of a true virus).

Regards,
and thanks for this great tool

pierre


2016-07-11 11:02 GMT+02:00 f8ttyc8t <notifications@github.com>:

> Hi Pierre,
> did you cross-check it using on-line scanners also?
> Because I created package but - at least I think so - my system is without
> any infections.
>
> Anyhow, thank you for informing us/me!
>
> (Btw. sorry for late reply, was at vacation...)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/QTodoTxt/QTodoTxt/issues/263#issuecomment-231679213>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AREtbarcN1Q5LNVkYz2LwBuKvbJSPb1Vks5qUgaNgaJpZM4I9k0X>
> .
>



-- 
pp




*« Il faut toujours plus de temps que prévu, même en tenant compte de la
Loi de Hofstadter. » « I enjoy the massacre of ads. This sentence will
slaughter ads without a messy bloodbath. » « C'est un crime contre l'Etat,
le suicide. Un suicidé, c'est un soldat de moins, un contribuable de moins.
» « Man is the best computer we can put aboard a spacecraft – and the only
one that can be mass-produced using unskilled labour. » (Wernher Von Braun)*
