### ISSUE TITLE
Debian package missing for Version 1.6.1

### ISSUE THREAD

**Issue by topas-rec** [QTodoTxt/QTodoTxt#266]
There is no packaged Ubuntu .deb package for version 1.6.1.
(I was able to generate one and attached it to this issue. The readme mentioned to contact the authors but I didn't find an email of anyone)
I didn't do any tests with the generated package. I found out that there should be done specific tests mentioned in the readme file but they are meant for altered sources I think. Please comment if I'm wrong or if something else is wrong with the package.
The package was generated using python3 on an Ubuntu 16.04 LTS.
[qtodotxt_1.6.1_all.deb.zip](https://github.com/QTodoTxt/QTodoTxt/files/384335/qtodotxt_1.6.1_all.deb.zip)

**Comment by oroulet** [comment]
Thanks! I will try to upload it, but I am without good network connection a few days

**Comment by topas-rec** [comment]
Nice. It would be nice to have a feedback of everything is okay with the package since I did  this for the first time.

**Comment by partnerwerk** [comment]
The package worked after I followed the instructions on prerequisites for version < 1.6

> To install on Linux:
> 
> and additionally, if qtodotxt version >= 1.6:
> 
>     Install PyQt5 (in Ubuntu: sudo apt-get install python3-pyqt5)
>     Install dateutil (in Ubuntu: sudo apt-get install python3-dateutil)
> 
Thank you for making it available

**Comment by topas-rec** [comment]
Perfect - than you for testing.

**Comment by oroulet** [comment]
should be done now

**Comment by topas-rec** [comment]
Double checked that the actual link points to a version 1.6.1 deb-file.
Issue closed.
