### ISSUE TITLE
1.6.0 How to delete tasks?

### ISSUE THREAD

**Issue by sercxanto** [QTodoTxt/QTodoTxt#268]
I just updated to version 1.6.0 on Windows. Deletion of tasks with "del" key is not longer working (compared to version 1.4). Also I didn't find a context menu entry.

**Comment by topas-rec** [comment]
I think I've seen something like "show delete task button" somewhere in the preferences or options in 1.6.1.
Can you try this?

**Comment by oroulet** [comment]
Will change default for next release.

**Comment by sercxanto** [comment]
Sorry and thanks for the hint. I didn't notice that this is an option now. In fact when this option is checked there is a entry in the context menu and the delete shortcut works like before.
