### ISSUE TITLE
Crash on very first start

### ISSUE THREAD

**Issue by fuchsmich** [QTodoTxt/QTodoTxt#273]
In an environmen where the app starts for the first time, it crashes:
`traceback (most recent call last):
  File "/usr/bin/qtodotxt", line 13, in <module>
    app.run()
  File "/usr/share/qtodotxt/bin/../qtodotxt/app.py", line 72, in run
    controller.show()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 174, in show
    self._updateView()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 381, in _updateView
    self.view.restoreGeometry(self._settings.value("main_window_geometry", b""))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'sip.voidptr'`

After commenting lines 381 and 382 the app starts.
On following runs it starts with original main_controller.py

**Comment by oroulet** [comment]
Thanks. Need to look at that one. I found a fix in another app I maintain

**Comment by swiesmann** [comment]
I just encountered the same issue. Thanks @fuchsmich for reporting and the temporary fix.

**Comment by oroulet** [comment]
https://github.com/QTodoTxt/QTodoTxt/pull/275

Please test

**Comment by swiesmann** [comment]
Worked for me :+1: I removed `~/.config/QTodoTxt` and after that it started without the error. Thanks!
