### ISSUE TITLE
minimize to tray

### ISSUE THREAD

**Issue by PKEv** [QTodoTxt/QTodoTxt#278]
Add the ability to minimize to tray when closing the app

**Comment by simonwiles** [comment]
would you be interested in a pull-request for this issue?  if so, would you want a preferences item to toggle this behaviour and the current behaviour, or do you have other ideas?

(For a while now I've been using a version of QTodoTxt 1.3 which I hacked to do this; I should be able to clean up my hacks and make sure they apply cleanly to the current trunk without too much difficulty.  Can't promise I could do it immediately, but could probably get around to it fairly soon.)

**Comment by oroulet** [comment]
All PR are welcome!

**Comment by oroulet** [comment]
Should be an option. Not everybody want that kind of things...

**Comment by PKEv** [comment]
closed by #279
