### ISSUE TITLE
Doesn't start/run on Ubuntu 16.04

### ISSUE THREAD

**Issue by mimf** [QTodoTxt/QTodoTxt#286]
I installed qtodo using the .deb that you provide. Upon trying to open it, I get the following error message:

```
Traceback (most recent call last):
  File "/usr/bin/qtodotxt", line 11, in <module>
    from qtodotxt import app
  File "/usr/share/qtodotxt/bin/../qtodotxt/app.py", line 13, in <module>
    from qtodotxt.ui.dialogs.taskeditor import TaskEditor
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/dialogs/taskeditor.py", line 2, in <module>
    from qtodotxt.ui.dialogs.taskeditor_dialog import TaskEditorDialog
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/dialogs/taskeditor_dialog.py", line 7, in <module>
    from dateutil.relativedelta import relativedelta
ImportError: No module named 'dateutil'
```

**Comment by PKEv** [comment]
Install dateutil (pip install python-dateutil)

**Comment by oroulet** [comment]
Then we should open a bug request. The deb should include dependency on dateutil

**Comment by oroulet** [comment]
Bug report

**Comment by oroulet** [comment]
Python3 dateutil?

**Comment by mimf** [comment]
I did "pip install python-dateutil". It installs python-dateutil 2.4, which, according to this [link](https://labix.org/python-dateutil), is for python3.

**Comment by oroulet** [comment]
On Ubuntu use pip3

**Comment by xtotdam** [comment]
As soon as none of the above didn't work for me, this helped:
`apt-get install python3-dateutil`

**Comment by PKEv** [comment]
everything according to the manual:
https://github.com/QTodoTxt/QTodoTxt/wiki

**Comment by xtotdam** [comment]
Oh, what was I looking at? Thanks
