### ISSUE TITLE
Question about multi-line

### ISSUE THREAD

**Issue by PKEv** [QTodoTxt/QTodoTxt#289]
Implementation of the multi-line task entry: was made a separate branch and it was abandoned... why?
what is the fundamental difficulty?

**Comment by oroulet** [comment]
Hi,
The implementation was half baked, completion were appearing at wrong
place, etc....
My main issue was that i really would like to remove the dialog altogether.
There is no point having such a dialog, we can add a new line in todo list
and override the default editor. I started working on it then discovered
the dialog code was really horrible, not following any qt best practices,
so i am still not finished.
So my plan is
1) make dialog a normal pop-up dialog ( not a global hidden widget that
appear when clicking on edit)
2) remove dialog
3) merge multiline if someone make a good implementation. New lines should
only be added if user reaches end of line

But this is an open source project, if you make a good implementation I
will merge. But someone should really fix 1.
