### ISSUE TITLE
Dark theme request

### ISSUE THREAD

**Issue by mimf** [QTodoTxt/QTodoTxt#290]
It would be fantastic if QToDoTxt provided a dark theme.

**Comment by lorentrogers** [comment]
Agreed. Blinding white kills my soul.

**Comment by PKEv** [comment]
Proposals, for the color scheme of the soul, are welcome for consideration

**Comment by lorentrogers** [comment]
https://github.com/AnthonyDiGirolamo/todotxt-machine uses base16 and solarized. Both of which are pretty rad.

**Comment by lorentrogers** [comment]
Poking through the code base, it looks like hard-coded color values are scattered throughout. I imagine we'd need to centralize this into a style sheet before we could look at changing themes in preferences. 

E.g. https://github.com/QTodoTxt/QTodoTxt/blob/master/qtodotxt/lib/task_htmlizer.py#L37

**Comment by oroulet** [comment]
Yes, qtodotxt is one of the last light applications on my desktop.
qt has its own theme engine, so it should be possible to select a dark theme. I tried but did not find out how it works, qtconfig does not work anymore for qt5. Then qtodotxt has probably some harcoded colors. Maybe should add an option to select between light or dark theme and switch colors accordingly. patch and/or information welcome

**Comment by lorentrogers** [comment]
I tried changing the CSS file, and it did change the colors. The issue is just that the hard-coded stuff overrides it. First step would be to move everything from hard-coded into the css file, I assume.

I found this commit that seems to address a lot of the colors:
https://github.com/QTodoTxt/QTodoTxt/commit/7cbacae8e8a20dd657a23fbf7b0545843abe3837

**Comment by oroulet** [comment]
I do not know anything about css in QT so I let you do the initial
investigations, or even better sen a patch ;-)

**Comment by PKEv** [comment]
As an example, I use the library:
https://github.com/ColinDuquesnoy/QDarkStyleSheet
![default](https://cloud.githubusercontent.com/assets/6053197/19798397/7ebcc288-9cf9-11e6-8251-bfbfbbf6d2d8.PNG)

**Comment by PKEv** [comment]
I think need to make a set of dark icons..

**Comment by oroulet** [comment]
How do you set style for qt? Can we do it programmatically? Put it in
options?

**Comment by PKEv** [comment]
All made according to the instructions in the library, add:
```
app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
```
in app.py , before 
```
app.exec_()
```

**Comment by oroulet** [comment]
Then we should add option for it.

**Comment by PKEv** [comment]
We must then prepare a dark icons (now looks not very good), and it is desirable to deal with the problems of selection #307

**Comment by PKEv** [comment]
in #119 the issue has been raised

**Comment by oroulet** [comment]
I do not think we need to make a GUI. But just an option to load a CSS
file. Should be easy to do. Then maybe have another set of icons for dark
themes but that is more work...

**Comment by lorentrogers** [comment]
@oroulet Agreed. I imagine this should be a simple CSS / icon swap. The issue will be pulling out all those hard-coded colors.

@PKEv could you put this into a PR that shows your changes?

**Comment by PKEv** [comment]
@lorentrogers 
to bring to the specified style, need settable specified package in the system, so I can not do PR - it is easier to do everything according to the instructions on the link

**Comment by lorentrogers** [comment]
@PKEv Do you mean that you just installed the package on your system and made no change to QTodoTxt? (I assume not?)

Did you import it as a package? Did you add this line somewhere? 

    app.setStyleSheet(qdarkstyle.load_stylesheet())

A PR would be helpful to see what changes you made to get it working in your code. Either that, or more info on how you made it work exactly.

**Comment by PKEv** [comment]
@lorentrogers 
look in my fork branch "try_darkstyle"
https://github.com/PKEv/QTodoTxt/tree/try_darkstyle
or 
https://github.com/PKEv/QTodoTxt/commit/7532bf38c65a8c244cff85fde25ea93945e008c2

you must first install QDarkStyleSheet by : 
```
pip install qdarkstyle
```

**Comment by PKEv** [comment]
@oroulet 
please look: 
https://github.com/PKEv/QTodoTxt/commit/43e32d0651d06a86b286384dc2d5eba115bdac94
https://github.com/PKEv/QTodoTxt/commit/73342084ead03f9d8d660aaa43ae74f48ec77438
Which style is more like it?

**Comment by PKEv** [comment]
dark blue:
![2016-11-10 00 03 00](https://cloud.githubusercontent.com/assets/6053197/20154596/8463465c-a6e1-11e6-948f-f2a0b8d9ad17.png)
or dark orange:
![2016-11-10 00 02 26](https://cloud.githubusercontent.com/assets/6053197/20154620/9bc83942-a6e1-11e6-834d-cd0b7b77d136.png)
It is necessary to adjust the backlight of tags in problems ...

**Comment by oroulet** [comment]
Both look very good in my opinion. Can we ship with both?

**Comment by PKEv** [comment]
In principle it is possible, but need to play with the color of the text, now it turns out that something cannot be read when the cursor hover on it

**Comment by oroulet** [comment]
As far as I remember the qt text fields do not support CSS, or they do?

**Comment by PKEv** [comment]
for this used class TaskHtmlizer

**Comment by oroulet** [comment]
Yes but all values are hard coded in that class...

On Thu, Nov 10, 2016, 08:52 PKEv <notifications@github.com> wrote:

for this used class TaskHtmlizer

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/QTodoTxt/QTodoTxt/issues/290#issuecomment-259623592>,
or mute the thread

**Comment by lorentrogers** [comment]
Awesome! Glad to see that we now have dark theme options!

I'll see if I can work up some alternative themes and send them along as a separate PR.

**Comment by mimf** [comment]
I find the blue in the toolbar to agressive. My suggestion would be either:

- A lighter tone of blue;
- Instead of having the whole icon blue, just have a tiny line or a tiny dot.

**Comment by PKEv** [comment]
@mimf 
This topic is locked, open a new one.
or even better - send pr
