### ISSUE TITLE
Delete task missing?

### ISSUE THREAD

**Issue by lorentrogers** [QTodoTxt/QTodoTxt#304]
Version 1.4 for mac lets me delete an entry via the edit menu. Dev master branch on linux does not. Did we loose a menu item at some point? Is there no shortcut to delete a task? (Seems like a major oversight...)

**Comment by oroulet** [comment]
Look at options, I put an option for it but it was a mistake. Should remove
it

**Comment by lorentrogers** [comment]
I see - this should probably be checked by default. I was hunting for it and didn't find it. This makes sense though; I could see someone wanting the option to disable it. (I imagine most folks would want to _enable_ it.)
