### ISSUE TITLE
Standardize the "quit" shortcut

### ISSUE THREAD

**Issue by lorentrogers** [QTodoTxt/QTodoTxt#305]
I've never seen `alt+F4` as the shortcut to quit an application. Is this a standard from somewhere? It seems like it makes more sense to have `ctrl+w` or `ctrl+q` be the default. (`option` on mac.) 

And, there should probably be a confirmation dialog before you exit, but that's probably worthy of a separate issue.

**Comment by oroulet** [comment]
No idea where the shortcuts come from. If you have ideas about standards,
send a PR

**Comment by lorentrogers** [comment]
Awesome--thanks!
