### ISSUE TITLE
Highlighting items after tab

### ISSUE THREAD

**Issue by lorentrogers** [QTodoTxt/QTodoTxt#307]
When I click on a context that's not currently selected, there's no indication of where my current selection is in the list on the right. (I assume there is none?)

However, if I then press the `tab` key twice, the list is now in focus, but there is still no selection indication. If I press the down arrow key, I get a "half-highlighted" state on the first item, but commands do not work on it. Pressing down again fully selects the item as I had expected.

I was expecting there to always be a current selection in the list, unless it's empty. If focus is in the list area, standard keys like `x` would always act on the current selection.

**Comment by oroulet** [comment]
Yes focused widget is not the same as selected. The best is usually to
stick to qt defaults, it is never perfect anyway. Try to find out if we do
special things with focus or selection...
