### ISSUE TITLE
More recent news?

### ISSUE THREAD

**Issue by lorentrogers** [QTodoTxt/QTodoTxt#312]
The news on http://qtodotxt.org/ hasn't been updated since 2014 -- is there something more recent we can put there? I assume info on the latest releases?

Alternatively, it may make most sense to scrap the news entirely from the site. If it won't get updated regularly, it'll only be confusing. Folks can still read the latest info on the project here.

**Comment by oroulet** [comment]
If you can clean up that. It would be great. That kind of things is hard to
maintain.  we need to simplify

**Comment by anacondaqq** [comment]
why download links about 1.4.0 version? Why not to upload latest one? For example from current build (29.10.2016) like: https://www.dropbox.com/s/36v9nsi6qblvp3k/qtodotxt_1.6.2_2016_10_29_GTD.exe?dl=0

**Comment by oroulet** [comment]
Fell free to fix links. Or Even better, simplify things. Make link to
download page in github

**Comment by lorentrogers** [comment]
@anacondaqq was there a link i missed? They should all be correct. If not, could you send a PR?

**Comment by lorentrogers** [comment]
Aah - I remember why this was an issue. I don't think the Mac build has been updated. Or, at least, I couldn't find it. So I kept the version text at 1.4 and linked to the 1.6 deb and exe files. 

It's probably easier if we just link right over to the download section of the readme, rather than maintaining it on the site.
