### ISSUE TITLE
Copy should pull current selection

### ISSUE THREAD

**Issue by lorentrogers** [QTodoTxt/QTodoTxt#324]
Pressing `Ctrl+C` should copy the currently selected todo item into the clipboard.

**Comment by PKEv** [comment]
the name of issue does not match the content

**Comment by lorentrogers** [comment]
Good point - updated.

**Comment by PKEv** [comment]
duplicate  #150

**Comment by lorentrogers** [comment]
Yaaay -- looks like it's handled.
