### ISSUE TITLE
Closing when deleting todo file

### ISSUE THREAD

**Issue by sttrebo** [QTodoTxt/QTodoTxt#328]
running the latest QTodoTxt from the sources.
If you inadvertently delete your todo.txt file, QTodoTxt immediately closes.  This is a new issue, but I'm not sure which recent merge caused this to happen.  I believe it's only been the last couple of merges since it was working fine a couple of weeks ago.

**Comment by PKEv** [comment]
I think it's #318
but it must show message, but not crashed
@sttrebo what is your system?
Write a sequence of actions

**Comment by sttrebo** [comment]
windows7-64 system
running QTodoTxt from source
todo file located in my DropBox folder
open up my DropBox folder and delete todo.txt file
QTodoTxt window closes.  no message, no window, no nothing.  it just disapears

**Comment by oroulet** [comment]
We can probably just add a try/except there and we will not crash. Looks
like qt crash if a there if an exception in a slot. Isn't it a new
behaviour? I did not see it before...
