### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by oroulet** [QTodoTxt/QTodoTxt#343]
@PKEv (And others) have done so much good work, maybe it is time for a new release? any important bug left?

**Comment by PKEv** [comment]
#341 necessarily ))

**Comment by PKEv** [comment]
Now all icons are icons in bulk in the internal directory and with the advent of the theme processing  their number may increase. (#347)
I suggest to create another repository for working with icons, and in the application to connect the compiled resources.
At the same time leave css files separately to interested persons could easily make their own changes

**Comment by oroulet** [comment]
@PKEv  I made you an owner of QTodoTxt group. You can now create new repositories, etc.
Welcome!

**Comment by PKEv** [comment]
Thank you, I will try to do everything carefully ))

**Comment by anacondaqq** [comment]
There some issues with building package:
```
C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\QTodoTxt-master\packaging\Windows>python setup.py py2exe
running py2exe
running build_py

  1 missing Modules
  ------------------
? readline                            imported from cmd, code, pdb
Building 'C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\QTodoTxt-master\packaging\Windows\dist\qtodotxt.exe'.
Building shared code archive 'C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\QTodoTxt-master\packaging\Windows\dist\library.zip'.
```

When trying to import readline module, pip says this module not supported on windows.
```
Collecting readline
  Using cached readline-6.2.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    error: this module is not meant to work on Windows
```

As result, qtodotxt.exe impossible to run, and here is stdrr error:
```
Traceback (most recent call last):
  File "qtodotxt.pyw", line 30, in <module>
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\app.py", line 71, in run
    controller = _createController(args)
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\app.py", line 56, in _createController
    window = MainView()
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\ui\views\main_view.py", line 16, in __init__
    self._initUI()
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\ui\views\main_view.py", line 27, in _initUI
    css = open(cssPath, 'r', encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\dev\\soft\\WinPython-64bit-3.4.4.4Qt5\\QTodoTxt-master\\packaging\\Windows\\dist\\resources\\css/default.css'
```

### Technical Information
1. hash: 8b737fdeed66c6c9969ace6c2116a1646be150cc
2. win10 x64, clean, no viruses, anniversary update (latest)
3. WinPython-64bit-3.4.4.4Qt5

##### Extra Suggestions:
Do not forget about installer.iss, and version inside it (1.6.1)

**Comment by PKEv** [comment]
What's the scheme of creation of an executive file? I have some sort of problem with installing py2exe...

**Comment by oroulet** [comment]
The error has nothing to do with py2exe. It seems to missing a file..

**Comment by oroulet** [comment]
beta version released on pip

**Comment by mimf** [comment]
How does one install the beta version via pip?

**Comment by oroulet** [comment]
Yes

**Comment by mimf** [comment]
What? I asked "how".. I mean, pip3 install qtodotxt-beta does not work.

**Comment by oroulet** [comment]
Written in readme pip install qtodotxt --pre -- upgrade
