### ISSUE TITLE
Light icons in dark theme

### ISSUE THREAD

**Issue by lorentrogers** [QTodoTxt/QTodoTxt#347]
With the dark themes enabled, the icons disappear against the background. We should have the ability to specify a light icon set for the dark themes, or use icons without transparent backgrounds.

![screenshot from 2016-11-11 11-41-02](https://cloud.githubusercontent.com/assets/1090824/20222629/0f4fb796-a804-11e6-90e0-0b4fb09599fb.png)

**Comment by PKEv** [comment]
What about this?
![default](https://cloud.githubusercontent.com/assets/6053197/20261521/31159cfc-aa6f-11e6-98c1-15904b818448.PNG)

**Comment by PKEv** [comment]
@oroulet ?

**Comment by oroulet** [comment]
Fine for me. I am not a designer..

**Comment by lorentrogers** [comment]
Definitely an improvement!
