### ISSUE TITLE
Web translation support

### ISSUE THREAD

**Issue by PKEv** [QTodoTxt/QTodoTxt#365]
@oroulet 
I have registered this project on https://hosted.weblate.org/projects/qtodotxt/
Please sign up there on the website that I could add you to the management

I hope this will help attract more people to the project...

**Comment by PKEv** [comment]
@oroulet please send me your email (pkev@ya.ru)

**Comment by PKEv** [comment]
you need first register on the site https://hosted.weblate.org/

**Comment by oroulet** [comment]
I am registered now. but I am personally not interested in translation..

**Comment by PKEv** [comment]
ok
