### ISSUE TITLE
Optional time in dates

### ISSUE THREAD

**Issue by ethingelstad** [QTodoTxt/QTodoTxt#372]
I have been a happy QTodoTxt user for a while now. But there is one thing I often miss: The ability to set a time for threshold dates so I can get back to it later the same day.

So I have fiddled a bit with the Python code to make it take the ISO 8601 format '2016-11-27T21:30' and it seems to work. If the datetime does not have a time component, it shows only the date. So this is an optional extension that changes nothing for those who only use dates.
	Example: (A) Make peace between Cylons and humans +PeaceProject t:2016-11-27T21:30

- ISO 8601 and the Todo.txt format rules collide on the use of colon in 'T21:30' here. I suggest using the colon, but I'm open for discussion.
- An area where I need some guidance is how and when to update the display.

But before I put more work into finishing this and creating a pull request, I want to know if this is an idea that has any chance of being accepted.
So what do you think about this?

**Comment by topas-rec** [comment]
I'm not a Dev team member but want to start the discussion.
I didn't need the exact time yet, but if it works as an extension I think it is okay. Maybe other people need it.
I regularly check my todo list so I don't need a specific time when tasks have to show up.

**Comment by oroulet** [comment]
I think that as long as you stick to the ISO format and that we can still use date only this would be a welcome PR.

I think that you should stick to ISO datetime string format. It should not be an issue. As far as I remember we only parse the first ':' in a string. And if we do not, we should ;-)

I do not sea any issue with display yet. But make PR early and we can comment.

**Comment by ethingelstad** [comment]
Thanks for the welcome!

I have forked, cloned and created a local branch called timeindates. Before incorporating my changes, I ran the tests as described in CONTRIBUTING.md to see that they worked. flake8 complained six times about 'E302 expected 2 blank lines, found 1' and py.test refused to run:
`.../QTodoTxt$ python3 -m py.test qtodotxt/test`
`/usr/lib/python3.5/runpy.py:125: RuntimeWarning: 'py.test' found in sys.modules after import of package 'py', but prior to execution of 'py.test'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/bin/python3: loader for pytest cannot handle py.test`

Do you get the same?
I have installed python3 3.5.1-4, flake8 3.0.4+dfsg1-1 and python3-pytest 2.9.2-3 from the Ubuntu 16.10 repositories. Are they old, or maybe I should install another way?
I'm a mechanical engineer that have also coded some C# on the side. This is my first foray into Python, so please be gentle. :)

**Comment by oroulet** [comment]
Create the pr then the test will be run on Travis and you will see the
result on github.
Your command looks complicated. Just run 'py.test tests'

**Comment by PKEv** [comment]
closed?
