### ISSUE TITLE
Menu not displaying in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by asitemade4u** [QTodoTxt/QTodoTxt#373]
Hi,
Thank you for this AMAZING application!
One little cosmetic issue though on Ubuntu 16.04. I cannot access the menu bar any longer whatever the choice made in Appearance [embedded menu bar or not].
This is annoying as I would like to change the theme I have set up [datrk + orange], which I do not like.
As an alternative, is it possible to access the preferences of the application then manually change them?

Please help.
Best,
Stephen

**Comment by asitemade4u** [comment]
I have found the location of the settings in Ubuntu:
~/.config/QTodoTxt/QTodoTxt.conf

**Comment by mabkenar** [comment]
On QTodoTxt 1.6.1 on Ubuntu 16.04 I can see the menus. And I can search through them using HUD. Which version are you using?

**Comment by oroulet** [comment]
Can we close this one?
