### ISSUE TITLE
qtodotxt.org domain

### ISSUE THREAD

**Issue by mNantern** [QTodoTxt/QTodoTxt#389]
Hi ! 

The domain qtodotxt.org will expire in 50 days (more or less).

I can continue to pay for it but maybe someone else want to manage it ?

What you think ?

**Comment by PKEv** [comment]
look:
 https://majestic.com/reports/site-explorer?folder=&q=qtodotxt.org&IndexDataSource=F
 http://www.alexa.com/siteinfo/qtodotxt.org

I do not want anything bad to say, but at this point it that it loses much in informativeness
@mNantern  Do you plan to change something on the site?

I do not want to lose a good domain name, but you have to decide what to do with it

**Comment by oroulet** [comment]
I do not feel like I have time to manage that in addition to code, so if
you could take care of it, it would be nice;-)

**Comment by mNantern** [comment]
Ok so I keep paying for the website, no change !

**Comment by oroulet** [comment]
Thanks!
