### ISSUE TITLE
Open CZK and SVK translation on weblate

### ISSUE THREAD

**Issue by Riko01** [QTodoTxt/QTodoTxt#395]
Hello, 

I would like to contribute with translation for CZK and SVK, please open languages on weblate.
Apologize if it doesnt belong here, do not know where to request.

Thank you.

**Comment by PKEv** [comment]
Please indicate which languages you are interested in?
Slovak & Czech ?

**Comment by PKEv** [comment]
ok

**Comment by PKEv** [comment]
https://hosted.weblate.org/projects/qtodotxt/translations/sk/
https://hosted.weblate.org/projects/qtodotxt/translations/cs/
We are pleased that you have taken part in this project!!!

**Comment by Riko01** [comment]
Thank you,

translations are ready.

Good luck with future versions

**Comment by PKEv** [comment]
all ready, please test it
